// actionTypes.js
export const FETCH_SHOWS_REQUEST = 'FETCH_SHOWS_REQUEST';
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS';
export const FETCH_SHOWS_FAILURE = 'FETCH_SHOWS_FAILURE';
export const FETCH_SHOW_SUMMARY_REQUEST = 'FETCH_SHOW_SUMMARY_REQUEST';
export const FETCH_SHOW_SUMMARY_SUCCESS = 'FETCH_SHOW_SUMMARY_SUCCESS';
export const FETCH_SHOW_SUMMARY_FAILURE = 'FETCH_SHOW_SUMMARY_FAILURE';
export const BOOK_TICKET = 'BOOK_TICKET';
export const CLEAR_SHOW_SUMMARY = 'CLEAR_SHOW_SUMMARY';
export const CLEAR_ERRORS = 'CLEAR_ERRORS'